import { DocumentTemplateService } from '../../pdf/templates/document-template.service';
import type { PDFOptions } from 'puppeteer';

export interface CompanyPdfSettings {
  logoUrl?: string;
  name?: string;
  partnerDescription?: string;
  addressLine1?: string;
  addressLine2?: string;
  region?: string;
  email?: string;
  tollFree?: string;
  cellNumbers?: string;
  gstNo?: string;
}

export interface TabularReportPdfData {
  title: string;
  filters: { label: string; value: string }[];
  metrics: { label: string; value: string; colorClass?: string }[];
  headers: string[];
  rows: string[][];
  company: CompanyPdfSettings;
}

export function renderTabularReportPdfOptions(
  company: CompanyPdfSettings,
  template: DocumentTemplateService,
): PDFOptions {
  return {
    displayHeaderFooter: true,
    headerTemplate: '<div></div>',
    footerTemplate: `
      <div style="width: 100%; font-family: 'Inter', Arial, sans-serif; font-size: 8px; color: #9ca3af; padding: 0 15mm; box-sizing: border-box; display: flex; justify-content: space-between; border-top: 1px solid #e5e7eb; pt: 3mm;">
        <span>Generated by ${template.escape(company.name || 'Mark Sorter')}</span>
        <span>Page <span class="pageNumber"></span> of <span class="totalPages"></span></span>
      </div>
    `,
    margin: {
      top: '12mm',
      right: '12mm',
      bottom: '16mm',
      left: '12mm',
    },
  };
}

export function renderTabularReportTemplate(
  data: TabularReportPdfData,
  template: DocumentTemplateService,
): string {
  const { title, filters, metrics, headers, rows, company } = data;
  const logoSrc = template.imageSrc(company.logoUrl);
  const companyLines = [
    company.addressLine1,
    company.addressLine2,
    company.region,
  ].filter(Boolean);

  const formattedFilters = filters
    .map(
      (f) =>
        `<div class="filter-item"><span class="filter-label">${template.escape(f.label)}:</span> <span class="filter-val">${template.escape(f.value)}</span></div>`,
    )
    .join('');

  const formattedMetrics = metrics
    .map(
      (m) => `
      <div class="metric-card">
        <div class="metric-val ${m.colorClass || ''}">${template.escape(m.value)}</div>
        <div class="metric-label">${template.escape(m.label)}</div>
      </div>
    `,
    )
    .join('');

  const tableHeaders = headers
    .map((h) => `<th>${template.escape(h)}</th>`)
    .join('');

  const tableRows = rows
    .map(
      (row) => `
      <tr>
        ${row.map((cell) => `<td>${cell}</td>`).join('')}
      </tr>
    `,
    )
    .join('');

  return `<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet">
  <style>
    @page { size: A4; }
    * { box-sizing: border-box; }
    body {
      margin: 0;
      color: #1f2937;
      font-family: 'Inter', Arial, sans-serif;
      font-size: 10px;
      line-height: 1.4;
      background: #fff;
      padding: 0;
    }
    .print-frame {
      width: 100%;
      border-collapse: collapse;
    }
    .print-frame > tbody > tr > td {
      border: 0;
      padding: 0;
    }
    
    /* Header layout */
    .document-header {
      display: flex;
      justify-content: space-between;
      align-items: start;
      border-bottom: 2px solid #f3f4f6;
      padding-bottom: 4mm;
      margin-bottom: 5mm;
    }
    .logo-container {
      width: 45mm;
      height: 18mm;
      display: flex;
      align-items: center;
    }
    .logo-img {
      max-width: 45mm;
      max-height: 18mm;
      object-fit: contain;
    }
    .company-details {
      text-align: right;
      font-size: 8.5px;
      color: #4b5563;
      line-height: 1.3;
    }
    .company-name {
      color: #ea580c; /* Orange branding */
      font-size: 16px;
      font-weight: 800;
      line-height: 1.1;
      margin-bottom: 1mm;
      text-transform: uppercase;
      letter-spacing: 0.5px;
    }
    .partner-tag {
      font-style: italic;
      color: #6b7280;
      margin-bottom: 1mm;
    }

    /* Report title & filters */
    .title-area {
      display: flex;
      justify-content: space-between;
      align-items: flex-end;
      margin-bottom: 5mm;
    }
    .report-title {
      font-size: 16px;
      font-weight: 800;
      color: #111827;
      margin: 0;
      letter-spacing: -0.2px;
      text-transform: capitalize;
    }
    .timestamp {
      font-size: 8.5px;
      color: #9ca3af;
      font-weight: 500;
    }
    
    .filters-bar {
      background: #f9fafb;
      border: 1px solid #f3f4f6;
      border-radius: 8px;
      padding: 3mm 4mm;
      margin-bottom: 5mm;
      display: flex;
      flex-wrap: wrap;
      gap: 4mm;
    }
    .filter-item {
      font-size: 9px;
    }
    .filter-label {
      font-weight: 700;
      color: #6b7280;
    }
    .filter-val {
      color: #111827;
      font-weight: 500;
    }

    /* Metrics widget */
    .metrics-container {
      display: grid;
      grid-template-columns: repeat(4, 1fr);
      gap: 4mm;
      margin-bottom: 6mm;
    }
    .metric-card {
      background: #ffffff;
      border: 1px solid #e5e7eb;
      border-radius: 12px;
      padding: 3.5mm 4mm;
      box-shadow: 0 1px 2px 0 rgba(0, 0, 0, 0.02);
    }
    .metric-val {
      font-size: 16px;
      font-weight: 800;
      color: #111827;
      line-height: 1.1;
      margin-bottom: 1mm;
    }
    .metric-val.text-primary {
      color: #ea580c;
    }
    .metric-val.text-success {
      color: #10b981;
    }
    .metric-val.text-info {
      color: #3b82f6;
    }
    .metric-val.text-warning {
      color: #f59e0b;
    }
    .metric-label {
      font-size: 8px;
      font-weight: 700;
      color: #9ca3af;
      text-transform: uppercase;
      letter-spacing: 0.5px;
    }

    /* Table styles */
    table.report-table {
      width: 100%;
      border-collapse: separate;
      border-spacing: 0;
      margin-bottom: 5mm;
    }
    table.report-table th,
    table.report-table td {
      padding: 2.5mm 3.5mm;
      text-align: left;
      vertical-align: middle;
      border-bottom: 1px solid #f3f4f6;
    }
    table.report-table th {
      background: #fafafa;
      color: #374151;
      font-weight: 700;
      font-size: 9px;
      text-transform: uppercase;
      letter-spacing: 0.5px;
      border-top: 1px solid #e5e7eb;
      border-bottom: 1.5px solid #d1d5db;
    }
    table.report-table td {
      font-size: 9px;
      color: #4b5563;
      word-break: break-word;
    }
    table.report-table tr:nth-child(even) td {
      background: #fafafa;
    }
    
    /* Utility classes */
    .status-badge {
      display: inline-flex;
      align-items: center;
      padding: 0.5mm 2mm;
      font-size: 7.5px;
      font-weight: 700;
      border-radius: 4px;
      text-transform: uppercase;
      letter-spacing: 0.3px;
    }
    .status-pending {
      background: rgba(245, 158, 11, 0.08);
      color: #d97706;
      border: 1px solid rgba(245, 158, 11, 0.15);
    }
    .status-inprogress {
      background: rgba(59, 130, 246, 0.08);
      color: #2563eb;
      border: 1px solid rgba(59, 130, 246, 0.15);
    }
    .status-completed {
      background: rgba(16, 185, 129, 0.08);
      color: #059669;
      border: 1px solid rgba(16, 185, 129, 0.15);
    }
    .status-cancelled {
      background: rgba(244, 63, 94, 0.08);
      color: #e11d48;
      border: 1px solid rgba(244, 63, 94, 0.15);
    }
    
    .font-semibold {
      font-weight: 600;
    }
    .font-bold {
      font-weight: 700;
    }
    .text-right {
      text-align: right;
    }
    .text-nowrap {
      white-space: nowrap;
    }
  </style>
</head>
<body>
  <table class="print-frame">
    <tbody>
      <tr>
        <td>
          <header class="document-header">
            <div class="logo-container">
              ${logoSrc ? `<img class="logo-img" src="${logoSrc}" alt="Company Logo" />` : ''}
            </div>
            <div class="company-details">
              <div class="company-name">${template.text(company.name, 'MENDO CONTROLS')}</div>
              ${company.partnerDescription ? `<div class="partner-tag">(${template.text(company.partnerDescription)})</div>` : ''}
              <div>${companyLines.map((line) => template.escape(line)).join('<br />')}</div>
              <div>${company.email ? `Email: ${template.escape(company.email)}` : ''}</div>
              <div>
                ${company.tollFree ? `Toll Free: ${template.escape(company.tollFree)}` : ''}
                ${company.cellNumbers ? ` | Cell: ${template.escape(company.cellNumbers)}` : ''}
              </div>
            </div>
          </header>

          <main>
            <div class="title-area">
              <h1 class="report-title">${template.text(title)}</h1>
              <span class="timestamp">Generated: ${template.date(new Date())}</span>
            </div>

            ${filters.length > 0 ? `<div class="filters-bar">${formattedFilters}</div>` : ''}

            ${metrics.length > 0 ? `<div class="metrics-container">${formattedMetrics}</div>` : ''}

            <table class="report-table">
              <thead>
                <tr>
                  ${tableHeaders}
                </tr>
              </thead>
              <tbody>
                ${tableRows.length > 0 ? tableRows : '<tr><td colspan="100" style="text-align: center; color: #9ca3af; padding: 10mm 0;">No matching records found.</td></tr>'}
              </tbody>
            </table>
          </main>
        </td>
      </tr>
    </tbody>
  </table>
</body>
</html>`;
}
