import * as Joi from 'joi';

export const validationSchema = Joi.object({
  NODE_ENV: Joi.string()
    .valid('development', 'production', 'test')
    .default('development'),
  PORT: Joi.number().default(4000),
  DATABASE_URL: Joi.string().required(),
  JWT_SECRET: Joi.string().required(),
  JWT_EXPIRES_IN: Joi.string().required(),
  JWT_REFRESH_SECRET: Joi.string().required(),
  JWT_REFRESH_EXPIRES_IN: Joi.string().required(),
  REDIS_HOST: Joi.string().default('localhost'),
  REDIS_PORT: Joi.number().default(6379),
  RABBITMQ_HOST: Joi.string().default('localhost'),
  RABBITMQ_PORT: Joi.number().default(5672),
  RABBITMQ_USER: Joi.string().default('admin'),
  RABBITMQ_PASS: Joi.string().default('admin'),
  RABBITMQ_VHOST: Joi.string().optional().allow(''),
  FOLDER_NAME: Joi.string().required(),
  BUCKET_NAME: Joi.string().required(),
  REGION: Joi.string().required(),
  ACCESS_KEY: Joi.string().required(),
  SECRET_ACCESS_KEY: Joi.string().required(),
  S3_BASE_URL: Joi.string().uri().required(),
  FIREBASE_PROJECT_ID: Joi.string().optional().allow(''),
  FIREBASE_CLIENT_EMAIL: Joi.string().optional().allow(''),
  FIREBASE_PRIVATE_KEY: Joi.string().optional().allow(''),
  SMTP_HOST: Joi.string().default('smtp.gmail.com'),
  SMTP_PORT: Joi.number().default(465),
  SMTP_USER: Joi.string().optional().allow(''),
  APP_PASSWORD: Joi.string().optional().allow(''),
  SMTP_FROM_NAME: Joi.string().default('Mark Sorting System'),
  FRONTEND_URL: Joi.string().uri().default('http://localhost:3000'),
});
